### ISSUE TITLE
Change Gabellink

### ISSUE THREAD

**Issue by Lodifice** [Lodifice/praedikat#9]
Currently, the Gabellink is shown as black text on a filled green rounded square.

It is desired that the Gabellink is shown as white text on a transparent rounded square with green border color (please choose a suitable border width, I'm thinking of something like 2–3 px).

Furthermore, the Gabellink text is not vertically centered within it's surrounding square, the opposite of which is overly desired.

**Comment by MarauderXtreme** [comment]
I require information for the light theme.

**Comment by Lodifice** [comment]
New idea: use fewer colors for a cleaner look.

Dark theme: keep text color white, but change the color of the box to be right as well.

Light theme: use the default font color for both text and box.
